In [23]:
import pickle as pkl
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
import os

In [25]:


def txt2df(path):

    user_sequences = defaultdict(list)

    with open(path, "r") as f:
        for line in f:
            parts = line.strip().split()
            user_id = int(parts[0])
            item_ids = list(map(int, parts[1:]))

            # append in order
            user_sequences[user_id].extend(item_ids)

    rows = []
    for user_id, items in user_sequences.items():
        for ts, item_id in enumerate(items):
            rows.append({
                "uid": user_id,
                "item_id": item_id+1,
                "timestamp": ts
            })

    df = pd.DataFrame(rows)
    return df

In [26]:
def txt2df2(path):

    rows = []

    with open(path, "r") as f:
        for line in f:
            parts = line.strip().split()
            user_id = int(parts[0])
            item_ids = list(map(lambda x: int(x)+1, parts[1:]))
            
            rows.append({
                "uid": user_id,
                "item_id": item_ids,
            })
            

    df = pd.DataFrame(rows)
    return df

In [30]:
txt2df2('Food/valid_data.txt')

       uid                                            item_id
0        4                           [46, 47, 48, 49, 50, 51]
1       15  [125, 126, 127, 128, 129, 130, 131, 132, 133, ...
2       21  [217, 218, 219, 220, 221, 222, 223, 224, 225, ...
3       25  [264, 265, 44, 266, 267, 268, 269, 270, 271, 2...
4       26                          [303, 304, 190, 305, 306]
...    ...                                                ...
1302  4653  [363, 524, 4830, 1829, 33, 517, 191, 518, 309,...
1303  4654                         [63, 1234, 6827, 43, 1880]
1304  4656            [428, 690, 29, 685, 1005, 306, 32, 737]
1305  4656  [606, 572, 52, 1262, 1297, 50, 193, 2518, 593,...
1306  4657  [2993, 8538, 6015, 6721, 8534, 2515, 5256, 114...

[1307 rows x 2 columns]

In [29]:
from pathlib import Path
for domain in os.listdir('.'):
    path = Path(domain)
    if path.is_dir() and domain[0].isupper():
        print(domain)
        tgt_path = os.path.join('/home/jovyan/Samra/fl-recsys-adaptation/data/FedData/', domain)
        os.makedirs(tgt_path, exist_ok=True)
        txt2df2(path / 'train_data.txt').to_parquet(tgt_path + '/train_.parquet')
        txt2df2(path / 'valid_data.txt').to_parquet(tgt_path + '/val_.parquet')
        txt2df2(path / 'test_data.txt').to_parquet(tgt_path + '/test_.parquet')

        n_items = int(open(path / 'num_items.txt').read())
        item_dict = {k:k for k in range(n_items)}
        pkl.dump(item_dict, open(tgt_path + '/item_id_to_idx.pkl', 'wb'))

Food

Games
Garden
Home
Kitchen
Movies
Sports
Beauty
Books
Clothing

In [32]:
pd.read_parquet('/home/jovyan/Samra/fl-recsys-adaptation/data/FedData/Food/val_.parquet')

       uid                                            item_id
0        4                           [46, 47, 48, 49, 50, 51]
1       15  [125, 126, 127, 128, 129, 130, 131, 132, 133, ...
2       21  [217, 218, 219, 220, 221, 222, 223, 224, 225, ...
3       25  [264, 265, 44, 266, 267, 268, 269, 270, 271, 2...
4       26                          [303, 304, 190, 305, 306]
...    ...                                                ...
1302  4653  [363, 524, 4830, 1829, 33, 517, 191, 518, 309,...
1303  4654                         [63, 1234, 6827, 43, 1880]
1304  4656            [428, 690, 29, 685, 1005, 306, 32, 737]
1305  4656  [606, 572, 52, 1262, 1297, 50, 193, 2518, 593,...
1306  4657  [2993, 8538, 6015, 6721, 8534, 2515, 5256, 114...

[1307 rows x 2 columns]